package com.giraffe.triplemapplication.model.customers

data class CustomerDetails(
    val id: Long,
    val email: String,
    val accepts_marketing: Boolean,
    val created_at: String,
    val updated_at: String,
    val first_name: String,
    val last_name: String,
    val orders_count: Int,
    val state: String,
    val total_spent: String,
    val last_order_id: Long?,
    val note: String?,
    val verified_email: Boolean,
    val multipass_identifier: String?,
    val tax_exempt: Boolean,
    val tags: String,
    val last_order_name: String?,
    val currency: String,
    val phone: String,
    val addresses: List<Address>,
    val accepts_marketing_updated_at: String,
    val marketing_opt_in_level: String?,
    val tax_exemptions: List<String>,
    val email_marketing_consent: EmailMarketingConsent,
    val sms_marketing_consent: SmsMarketingConsent,
    val admin_graphql_api_id: String,
    val default_address: Address
)
